title:       gitbook
description: 描述

theme: null


#url: "http://127.0.0.1:4000"
url: "https://xymeng.xyz" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "gitbook"


# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
